name: qgEnv
channels:
  - defaults
dependencies:
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - async-timeout=4.0.1
  - attrs=21.4.0
  - blas=1.0
  - boto3=1.21.32
  - botocore=1.24.32
  - brotli=1.0.9
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2022.3.29
  - cachetools=4.2.2
  - catalogue=2.0.6
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.4
  - cryptography=36.0.0
  - cycler=0.11.0
  - cymem=2.0.5
  - cython-blis=0.7.4
  - dataclasses=0.8
  - fonttools=4.25.0
  - freetype=2.11.0
  - frozenlist=1.2.0
  - giflib=5.2.1
  - google-api-core=1.25.1
  - google-auth=1.33.0
  - google-cloud-core=1.7.1
  - google-cloud-storage=1.41.0
  - google-crc32c=1.1.2
  - google-resumable-media=1.3.1
  - googleapis-common-protos=1.53.0
  - grpcio=1.42.0
  - idna=3.3
  - intel-openmp=2021.4.0
  - jinja2=3.0.3
  - jmespath=0.10.0
  - joblib=1.1.0
  - jpeg=9d
  - kiwisolver=1.3.2
  - langcodes=3.3.0
  - lcms2=2.12
  - libcrc32c=1.1.1
  - libffi=3.3
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - libtiff=4.2.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.2.0
  - munkres=1.1.4
  - murmurhash=1.0.5
  - ncurses=6.3
  - networkx=2.7.1
  - nltk=3.7
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1n
  - packaging=21.3
  - pathy=0.6.0
  - pillow=9.0.1
  - pip=21.2.4
  - preshed=3.0.5
  - protobuf=3.19.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pydantic=1.8.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - pytz=2021.3
  - readline=8.1.2
  - regex=2022.3.15
  - requests=2.27.1
  - rsa=4.7.2
  - s3transfer=0.5.0
  - scipy=1.7.3
  - setuptools=58.0.4
  - shellingham=1.3.1
  - six=1.16.0
  - smart_open=5.1.0
  - spacy=3.2.1
  - spacy-legacy=3.0.8
  - spacy-loggers=1.0.1
  - sqlite=3.38.2
  - srsly=2.4.1
  - thinc=8.0.13
  - tk=8.6.11
  - tornado=6.1
  - tqdm=4.63.0
  - typer=0.4.0
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - urllib3=1.26.8
  - wasabi=0.8.2
  - wheel=0.37.1
  - xz=5.2.5
  - yarl=1.5.1
  - zlib=1.2.11
  - zstd=1.4.9

